### ISSUE TITLE
Step 6 "run the Python code" failed for many times

### ISSUE THREAD

**Issue by yihuajack** [YuchuanTian/VMkiller#1]
In README it is descripted that "This may fail; retry this step until it works", however, what kind of failure there would be? In my environment, I got the following error:
```
Traceback (most recent call last):
  File "D:\Documents\GitHub\VMkiller\VMkiller.py", line 42, in <module>
    windowOutshow()
  File "D:\Documents\GitHub\VMkiller\VMkiller.py", line 38, in windowOutshow
    win32gui.SetForegroundWindow(hwnd)
pywintypes.error: (1400, 'SetForegroundWindow', '无效的窗口句柄。')
```
Was I on the proper way or missed any important points? I did minimize my remote desktop window and had retried for many times.

**Comment by yihuajack** [comment]
Problem solved. Need to change the IP address in the name of the window in VMkiller.py.

**Comment by YuchuanTian** [comment]
Yes exactly
